# Generated by Django 6.0.4 on 2026-04-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='資産名')),
                ('cloud_id', models.CharField(default=None, max_length=255, null=True, unique=True, verbose_name='クラウドID')),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('gcp', 'GCP'), ('azure', 'Azure'), ('on_premise', 'オンプレミス')], max_length=50, verbose_name='プロバイダー')),
                ('asset_type', models.CharField(choices=[('compute', 'コンピュート'), ('database', 'データベース'), ('storage', 'ストレージ'), ('network', 'ネットワーク'), ('other', 'その他')], max_length=50, verbose_name='資産タイプ')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='リージョン')),
                ('endpoint', models.URLField(blank=True, null=True, verbose_name='接続先エンドポイント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name': '資産',
                'verbose_name_plural': '資産',
            },
        ),
    ]
