# Generated by Django 6.0.4 on 2026-05-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0002_application_environment_system_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('EC2', 'EC2 Instance'), ('RDS', 'RDS Instance'), ('ALB', 'Application Load Balancer'), ('VPC', 'VPC'), ('S3', 'S3 Bucket'), ('EBS', 'EBS Volume'), ('ECS', 'ECS Service'), ('TG', 'Target Group'), ('LISTENER', 'Listener'), ('OTHER', 'Other')], max_length=20, verbose_name='資産タイプ'),
        ),
    ]
