# Generated by Django 5.2.5 on 2026-05-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0012_system_scan_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='slack_webhook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Slack Webhook URL'),
        ),
    ]
