# Generated by Django 5.2.5 on 2026-05-30 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0013_system_slack_webhook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appdependency',
            options={'ordering': ['dep_type', 'name'], 'verbose_name': 'Dependency', 'verbose_name_plural': 'Dependencies'},
        ),
        migrations.AlterModelOptions(
            name='appenvconfig',
            options={'ordering': ['application', 'environment'], 'verbose_name': 'App Environment Config', 'verbose_name_plural': 'App Environment Configs'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['system', 'name'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ['system', 'env_type'], 'verbose_name': 'Environment', 'verbose_name_plural': 'Environments'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='scanjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Scan Job', 'verbose_name_plural': 'Scan Jobs'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['name'], 'verbose_name': 'System', 'verbose_name_plural': 'Systems'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='environment',
            name='backend_type',
            field=models.CharField(choices=[('manual', 'Manual Upload'), ('s3', 'S3 Remote State')], default='manual', max_length=20, verbose_name='State Backend'),
        ),
        migrations.AddField(
            model_name='environment',
            name='s3_bucket',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Bucket'),
        ),
        migrations.AddField(
            model_name='environment',
            name='s3_key',
            field=models.CharField(blank=True, help_text='e.g. envs/prod/terraform.tfstate', max_length=1024, null=True, verbose_name='S3 Key'),
        ),
        migrations.AddField(
            model_name='environment',
            name='s3_region',
            field=models.CharField(blank=True, help_text='e.g. ap-northeast-1', max_length=50, null=True, verbose_name='S3 Region'),
        ),
        migrations.AlterField(
            model_name='appdependency',
            name='app_env_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='asset_manager.appenvconfig', verbose_name='App Env Config'),
        ),
        migrations.AlterField(
            model_name='appdependency',
            name='dep_type',
            field=models.CharField(choices=[('library', 'Library'), ('middleware', 'Middleware'), ('tool', 'Tool')], default='library', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='appdependency',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Package Name'),
        ),
        migrations.AlterField(
            model_name='appdependency',
            name='version',
            field=models.CharField(max_length=100, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='appenvconfig',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_configs', to='asset_manager.application', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='appenvconfig',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='appenvconfig',
            name='db_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_db_configs', to='asset_manager.asset', verbose_name='Database Asset'),
        ),
        migrations.AlterField(
            model_name='appenvconfig',
            name='deploy_method',
            field=models.CharField(choices=[('ec2', 'EC2'), ('ecs', 'ECS (Fargate/EC2)'), ('lambda', 'Lambda'), ('k8s', 'Kubernetes'), ('beanstalk', 'Elastic Beanstalk'), ('other', 'Other')], default='ec2', max_length=20, verbose_name='Deploy Method'),
        ),
        migrations.AlterField(
            model_name='appenvconfig',
            name='deploy_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_deploy_configs', to='asset_manager.asset', verbose_name='Deploy Target'),
        ),
        migrations.AlterField(
            model_name='appenvconfig',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_configs', to='asset_manager.environment', verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='appenvconfig',
            name='framework_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Framework Version'),
        ),
        migrations.AlterField(
            model_name='appenvconfig',
            name='language_version',
            field=models.CharField(max_length=50, verbose_name='Language Version'),
        ),
        migrations.AlterField(
            model_name='appenvconfig',
            name='runtime',
            field=models.CharField(choices=[('apache', 'Apache'), ('nginx', 'Nginx'), ('puma', 'Puma'), ('unicorn', 'Unicorn'), ('uwsgi', 'uWSGI'), ('gunicorn', 'Gunicorn'), ('node', 'Node.js'), ('none', 'None / Other')], default='nginx', max_length=20, verbose_name='Runtime'),
        ),
        migrations.AlterField(
            model_name='appenvconfig',
            name='runtime_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Runtime Version'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='application',
            name='framework',
            field=models.CharField(choices=[('laravel', 'Laravel'), ('rails', 'Ruby on Rails'), ('django', 'Django'), ('fastapi', 'FastAPI'), ('flask', 'Flask'), ('nextjs', 'Next.js'), ('nuxtjs', 'Nuxt.js'), ('react', 'React'), ('vue', 'Vue.js'), ('angular', 'Angular'), ('spring', 'Spring Boot'), ('express', 'Express'), ('nestjs', 'NestJS'), ('none', 'None / Other')], default='none', max_length=20, verbose_name='Framework'),
        ),
        migrations.AlterField(
            model_name='application',
            name='language',
            field=models.CharField(choices=[('php', 'PHP'), ('ruby', 'Ruby'), ('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('go', 'Go'), ('java', 'Java'), ('kotlin', 'Kotlin'), ('rust', 'Rust'), ('other', 'Other')], max_length=20, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, verbose_name='App Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='repository_url',
            field=models.URLField(blank=True, null=True, verbose_name='Repository URL'),
        ),
        migrations.AlterField(
            model_name='application',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='asset_manager.system', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_category',
            field=models.CharField(db_index=True, default='OTHER', max_length=20, verbose_name='Asset Category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(max_length=50, verbose_name='Asset Type'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cloud_id',
            field=models.CharField(default='-', max_length=255, unique=True, verbose_name='Cloud ID'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='endpoint',
            field=models.TextField(blank=True, null=True, verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset_manager.environment', verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_imported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Imported At'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Asset Name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='provider',
            field=models.CharField(default='AWS', max_length=20, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='raw_data_prev',
            field=models.JSONField(blank=True, default=dict, verbose_name='Previous Raw Data'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='env_type',
            field=models.CharField(choices=[('PROD', 'Production'), ('STG', 'Staging'), ('DEV', 'Development'), ('QA', 'QA')], default='DEV', max_length=20, verbose_name='Environment Type'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Environment Name'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='asset_manager.system', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='tfstate_filename',
            field=models.CharField(blank=True, help_text='Corresponding tfstate filename (e.g. ecsite-prod.tfstate)', max_length=255, null=True, verbose_name='tfstate Filename'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='asset_manager.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('INFRA_ADMIN', 'Infra Admin'), ('APP_ADMIN', 'App Admin'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='created_count',
            field=models.PositiveIntegerField(default=0, verbose_name='New Assets'),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished At'),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='regions',
            field=models.JSONField(default=list, verbose_name='Scan Regions'),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='asset_manager.system', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='updated_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Updated Assets'),
        ),
        migrations.AlterField(
            model_name='system',
            name='aws_scan_regions',
            field=models.JSONField(blank=True, default=list, verbose_name='Scan Regions'),
        ),
        migrations.AlterField(
            model_name='system',
            name='code',
            field=models.SlugField(unique=True, verbose_name='System Code'),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='system',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems', to='asset_manager.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='system',
            name='scan_enabled',
            field=models.BooleanField(default=False, verbose_name='Auto Scan'),
        ),
        migrations.AlterField(
            model_name='system',
            name='scan_interval_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Scan Interval (min)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, verbose_name='TOTP Secret'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Two-Factor Auth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
