# Generated by Django 6.0.5 on 2026-06-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0015_environment_s3_auto_sync'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit log', 'verbose_name_plural': 'Audit logs'},
        ),
    ]
