# Generated by Django 6.0.5 on 2026-06-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0016_alter_auditlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='slack_language',
            field=models.CharField(choices=[('en', 'English'), ('ja', '日本語')], default='en', help_text='Language used for Slack drift notifications.', max_length=5, verbose_name='Slack Notification Language'),
        ),
    ]
