# Generated by Django 6.0.5 on 2026-06-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0017_system_slack_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='EolSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='EOL Data')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Fetched At')),
                ('source', models.CharField(default='endoflife.date', max_length=255, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'EOL Snapshot',
                'verbose_name_plural': 'EOL Snapshots',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
