# Generated by Django 5.2.5 on 2026-06-16 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0018_eolsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='管理用備考', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('source', models.CharField(choices=[('scan', 'AWS Scan'), ('tfstate', 'tfstate Import'), ('s3-sync', 'S3 Sync')], default='scan', max_length=20, verbose_name='Source')),
                ('changed_count', models.PositiveIntegerField(default=0, verbose_name='Changed')),
                ('added_count', models.PositiveIntegerField(default=0, verbose_name='Added')),
                ('unchanged_count', models.PositiveIntegerField(default=0, verbose_name='Unchanged')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Detail')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Detected At')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_snapshots', to='asset_manager.environment', verbose_name='Environment')),
            ],
            options={
                'verbose_name': 'Drift Snapshot',
                'verbose_name_plural': 'Drift Snapshots',
                'ordering': ['-detected_at'],
            },
        ),
    ]
