# Generated by Django 5.2.5 on 2026-08-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0019_driftsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='missing_since',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Missing Since'),
        ),
        migrations.AddField(
            model_name='driftsnapshot',
            name='removed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Removed'),
        ),
    ]
