"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(key, default=False):
    return os.getenv(key, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


# テスト実行中か（manage.py test / pytest / IDE）
_is_testing = (
    'test' in sys.argv
    or os.path.basename(sys.argv[0]) in ('pytest', '_jb_pytest_runner.py')
    or 'pytest' in sys.modules
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', False)

# SECURITY WARNING: keep the secret key used in production secret!
_INSECURE_SECRET_KEY = 'django-insecure-change-me-in-production'  # nosec B105 - 意図的プレースホルダ（本番では起動拒否）
SECRET_KEY = os.getenv('SECRET_KEY', _INSECURE_SECRET_KEY)
if not DEBUG and not _is_testing and SECRET_KEY == _INSECURE_SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY must be set to a unique secret value when DEBUG=False. "
        "Set the SECRET_KEY environment variable."
    )

# 本番は ALLOWED_HOSTS を環境変数で明示（カンマ区切り）。DEBUG時のみワイルドカード許可。
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]
if DEBUG:
    ALLOWED_HOSTS = ['*']
elif not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# HTTPS 配下でフォーム POST する場合に必要（例: https://syncvey.example.com）
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# --- セキュリティ・ハードニング（HTTPS終端の背後で運用する場合に各env で有効化）---
SECURE_CONTENT_TYPE_NOSNIFF = True
if _env_bool('SECURE_PROXY_SSL_HEADER', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Cookie は本番デフォルト Secure（HTTP のみで運用する場合は明示的に False を設定）
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE    = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)
# 以下は環境依存が大きいため既定 OFF（HTTPS 運用時に env で有効化）
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', False)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0') or '0')
if SECURE_HSTS_SECONDS:
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', True)

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My apps
    'asset_manager.apps.AssetManagerConfig',
    # Optional / detachable plugin apps (discovered via asset_manager.plugins).
    # Remove this line and the core hides the nav entry and 404s its routes.
    'syncvey_drift_risk.apps.DriftRiskConfig',
    'syncvey_blast_radius.apps.BlastRadiusConfig',
    'django_apscheduler',
]

APSCHEDULER_DATETIME_FORMAT = "Y-m-d H:i:s"
APSCHEDULER_RUN_NOW_TIMEOUT = 25

# --- Feature flags / plugins ------------------------------------------------
# Optional / advanced features are kept detachable (see asset_manager/plugins.py).
# Toggle a feature with an env var, e.g.
#   FEATURE_DRIFT_HISTORY=false
# Installable plugin apps (AppConfig.syncvey_plugin = True) can be added here.
SYNCVEY_FEATURES = {
    key[len('FEATURE_'):].lower(): _env_bool(key)
    for key in os.environ
    if key.startswith('FEATURE_')
}

if DEBUG and not _is_testing:
    INSTALLED_APPS += ['debug_toolbar']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'asset_manager.middleware.OrgRequiredMiddleware',
    'asset_manager.middleware.SecurityHeadersMiddleware',
    'asset_manager.middleware.AuditMiddleware',
]

# Referrer-Policy（Django の SecurityMiddleware が付与）
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

if DEBUG and not _is_testing:
    MIDDLEWARE = ['debug_toolbar.middleware.DebugToolbarMiddleware'] + MIDDLEWARE

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'asset_manager.context_processors.features',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 環境変数 DATABASE_URL からデータベース設定を読み込む
DATABASE_URL = os.getenv('DATABASE_URL')
DATABASES = {'default': dj_database_url.parse(DATABASE_URL)}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Default to English; LocaleMiddleware switches to Japanese based on the
# browser's Accept-Language header (falls back to LANGUAGE_CODE otherwise).
LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('ja', '日本語'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# AWS Settings (AssumeRole用 中央アカウント)
AWS_ACCOUNT_ID    = os.getenv('AWS_ACCOUNT_ID', '')
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_SCAN_REGIONS  = os.getenv('AWS_SCAN_REGIONS', 'ap-northeast-1').split(',')

# Slack通知（共通チャンネル。システム個別設定が優先）
SLACK_WEBHOOK_URL = os.getenv('SLACK_WEBHOOK_URL', '')

# EOL データの外部取得（endoflife.date）。既定OFF＝外部通信なし（静的辞書のみ）。
#   EOL_REFRESH_ENABLED=true で日次取得を有効化（オプトイン）。
#   EOL_REFRESH_DYNAMIC=false で取得対象を固定ベースセットに限定（DB依存名からの動的導出を無効化）。
EOL_REFRESH_ENABLED = _env_bool('EOL_REFRESH_ENABLED', False)
EOL_REFRESH_DYNAMIC = _env_bool('EOL_REFRESH_DYNAMIC', True)

# ドリフト履歴の保持件数（Environment ごと）。スキャン／取込／S3同期のたびに
# 差分ゼロでも1行積むため、未設定だとテーブルが無限に伸びる。0 以下で無制限。
DRIFT_SNAPSHOT_RETENTION = int(os.getenv('DRIFT_SNAPSHOT_RETENTION', '500') or '0')

# 週次ドリフト・ブリーフィング（syncvey_drift_risk プラグイン）。既定OFF＝
# 外部送信なし。true でスケジューラに毎週月曜 09:00 のジョブを登録し、Slack
# Webhook を設定済みのシステムへサマリを送る（オプトイン）。
DRIFT_DIGEST_ENABLED = _env_bool('DRIFT_DIGEST_ENABLED', False)

# Secrets Manager のローテーション許容日数（syncvey_drift_risk プラグイン）。
# 有効なのに最後のローテーションからこの日数を超えた secret は「起きるべき
# ローテーションが起きていない」ドリフトとして点灯する。2倍を超えると critical。
SECRET_ROTATION_MAX_AGE_DAYS = int(os.getenv('SECRET_ROTATION_MAX_AGE_DAYS', '90') or '90')

# Debug toolbar (Docker環境でも表示可能にする)
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
}
